package com.weebmeister.seife.anno;

/**
 * Additional options for the SQL layer
 * @author Klaus Sausen
 */
public @interface SqlFieldOptions {
	
	/**
	 * Explicitly specify column name if not autogenerated
	 * @return default to empty string
	 */
	String sqlColumn() default "";
	
	/**
	 * Add the column to the specified index if applicable,
	 * a field can be part of multiple indexes
	 * @return array of strings
	 */
	String[] sqlIndex() default {};
	
    /**
     * DB: specify whether the field is unique, option is ignored if isPrimaryKey is set to true.
	 * @return array of strings
     */
    String[] uniqueGroup() default {};
    
	/**
	 * The sql default value
	 * @return default content is empty string
	 */
	String sqlDefault() default "";
	
	/**
	 * Override the sql type to use
	 * @return default content is empty string
	 */
	String sqlType() default "";

	/**
	 * If the field is a primary key the default is to have the auto increment enabled
	 * @return default is true
	 */
	boolean sqlAutoIncrement() default true;
}
